Sprint 3/step 1
akyc/react-burger pull request #4
Opened 2023-11-13 06:38 UTC by akyc

Роутинг, реализация механизмов авторизации.

2023-11-13 09:11 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая работа с формами
- Есть автологин
- Есть защита роутов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Модалка должна закрываться нажатием на подложку
- При изменении данных юзера на странице профиля в payload запроса ничего не уходит - пустой объект.
![image](https://github.com/akyc/react-burger/assets/60173362/3c1a1c43-9f5e-4964-8f6a-22ad2496c15b)
- После успешного прохождения запроса на регистрацию необходимо переводить юзера на главную страницу под авторизованных акаунтом.
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Можете посоветоваться с наставником.
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Для этого используйте обертку над fetch, примерно такую
```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-13 09:11 UTC, andryxxa93 commented on src/components/App/App.js
> +                  <Route path='/register' element={<Register />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-11-13 09:11 UTC, andryxxa93 commented on src/pages/forgot-password/forgot-password.js
> +    const login = JSON.parse(sessionStorage.getItem('login'));
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-11-14 05:57 UTC, akyc commented
Поправил все замечания помеченные как необходимо исправить.

2023-11-14 07:16 UTC, andryxxa93 reviewed
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-28 03:55 UTC, merged